language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
# command to run tests
script: coverage run --branch --source=libmodernize setup.py test
# Ensure dependencies are installed
install:
  - pip install .
  - pip install 'coveralls==0.4.2'
  - pip install 'six >= 1.8.0'
after_success:
  coveralls
